language: "node_js"
node_js: "12"

script:
  - npm run test
  - npm run lint
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: $KEY
  skip-cleanup: true
  keep_history: true
  on:
    branch: master
