language: 'node_js'
node_js: '8'

script:
  - npm run test
  - npm run lint

deploy:
  local_dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  repo: NadiaPOI/Puissance-4-React-App
  target_branch: gh-pages
  on:
    branch: master
